param([string]$Rom, [string]$Bios, [string]$Generator)
. "$PSScriptRoot\common.ps1"
if (-not $Rom) { $Rom = $DefaultRom }
if (-not $Bios) { $Bios = $DefaultBios }
if (-not $Generator) {
    $Generator = "$ProjectRoot\build\host\framework\gba_recompile.exe"
    if (-not (Test-Path -LiteralPath $Generator)) { throw 'Build the pinned generator first: tools/build-host.ps1 -GeneratorOnly' }
}
Assert-Rom $Rom
Assert-Bios $Bios
New-Item -ItemType Directory -Force -Path "$ProjectRoot\logs" | Out-Null
Invoke-Logged $Generator @('--rom',$Rom,'--config',"$ProjectRoot\game.toml",'--out',"$ProjectRoot\generated\cart",'--max-functions','65536') "$ProjectRoot\logs\regen-cart.log"
Invoke-Logged $Generator @('--bios',$Bios,'--config',"$ProjectRoot\gbarecomp\bios\gba_bios.toml",'--out',"$ProjectRoot\generated\bios") "$ProjectRoot\logs\regen-bios.log"
# This generic framework support header is tracked upstream, not generated by
# gba_recompile. External BIOS output needs it beside the translated sources.
$support = "$ProjectRoot\gbarecomp\src\runtime\generated_bios\codegen_tail_macros.h"
if (Test-Path -LiteralPath $support) {
    Copy-Item -LiteralPath $support -Destination "$ProjectRoot\generated\bios\codegen_tail_macros.h" -Force
}
Get-Content -LiteralPath "$ProjectRoot\logs\regen-cart.log" -Tail 8
Get-Content -LiteralPath "$ProjectRoot\logs\regen-bios.log" -Tail 4
